name: Deploy to Snowflake

on:
  push:
    branches:
      - dev
      - uat
      - prod
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install SnowSQL
        run: |
          sudo apt-get update && sudo apt-get install -y unzip
          mkdir -p $HOME/snowsql_install
          wget https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.21-linux_x86_64.bash
          bash snowsql-1.2.21-linux_x86_64.bash -y -d $HOME/snowsql_install
          echo "$HOME/snowsql_install/bin" >> $GITHUB_PATH

      - name: Deploy SQL Scripts
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
        run: |
          snowsql -a $SNOWFLAKE_ACCOUNT \
                  -u $SNOWFLAKE_USER \
                  -p $SNOWFLAKE_PASSWORD \
                  -r $SNOWFLAKE_ROLE \
                  -w $SNOWFLAKE_WAREHOUSE \
                  -d $SNOWFLAKE_DATABASE \
                  -s $SNOWFLAKE_SCHEMA \
                  -f sql/deploy.sql

      - name: Archive deployed file
        run: |
          TIMESTAMP=$(date +'%Y-%m-%dT%H-%M')
          BRANCH=$(echo "${{ github.ref_name }}" | tr '/' '-')
          ARCHIVE_DIR="archive"
          ARCHIVE_FILE="$ARCHIVE_DIR/deploy_${TIMESTAMP}_${BRANCH}.sql"

          mkdir -p $ARCHIVE_DIR
          mv sql/deploy.sql $ARCHIVE_FILE

          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add $ARCHIVE_FILE
          git rm sql/deploy.sql
          git commit -m "Archived deploy.sql as $ARCHIVE_FILE after successful deployment"
          git push
