name: Deploy to Snowflake (schemachange)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install schemachange
        run: pip install schemachange

      - name: Generate connections.toml
        run: |
          cat << EOF > connections.toml
          [ci_connection]
          account = "${{ secrets.SNOWFLAKE_ACCOUNT }}"
          user = "${{ secrets.SNOWFLAKE_USER }}"
          password = "${{ secrets.SNOWFLAKE_PASSWORD }}"
          role = "${{ secrets.SNOWFLAKE_ROLE }}"
          warehouse = "${{ secrets.SNOWFLAKE_WAREHOUSE }}"
          database = "${{ secrets.SNOWFLAKE_DATABASE }}"
          schema = "${{ secrets.SNOWFLAKE_SCHEMA }}"
          EOF
          
      - name: Set permissions for connections.toml
        run: chmod 600 connections.toml

      - name: Run schemachange
        run: |
          schemachange \
            -f ./sql \
            --connection-name ci_connection \
            --connections-file-path ./connections.toml \
            --create-change-history-table
