name: Deploy SnowSQL Scripts to Snowflake

on:
  push

env:
  SNOWSQL_VERSION: 1.4.4
  SNOWSQL_DIR: $HOME/snowsql

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 📂 Checkout repository
        uses: actions/checkout@v4

      - name: 🧾 Print Inputs
        run: |
          echo "Environment: ${{ github.event.inputs.environment }}"

      - name: 🧪 Verify runner context
        run: |
          echo "USER: $(whoami)"
          echo "HOME: $HOME"
          echo "PWD: $(pwd)"
          echo "Shell: $SHELL"
          echo "PATH: $PATH"
          env

      - name: 🧊 Install SnowSQL v1.4.4
        shell: bash
        run: |
          #!/usr/bin/env bash
          set -euo pipefail
      
          # 🧩 Set environment variables
          export SNOWSQL_VERSION="1.4.4"
          export SNOWSQL_DIR="$HOME/snowsql"
          export SNOWSQL_INSTALLER="snowsql-${SNOWSQL_VERSION}-linux_x86_64.bash"
          export SNOWSQL_URL="https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/${SNOWSQL_VERSION}/linux_x86_64/${SNOWSQL_INSTALLER}"
      
          echo "📦 Installing SnowSQL version $SNOWSQL_VERSION..."
          echo "📁 Installation directory: $SNOWSQL_DIR"
      
          # 📥 Download the correct SnowSQL installer
          mkdir -p "$SNOWSQL_DIR"
          curl -# -L -o "$SNOWSQL_DIR/$SNOWSQL_INSTALLER" "$SNOWSQL_URL"
          chmod +x "$SNOWSQL_DIR/$SNOWSQL_INSTALLER"
      
          echo "🛠️ Patching installer to skip interactive prompt..."
          # Patch to disable prompt by pre-defining SNOWSQL_DEST
          sed -i.bak '/read -p.*SNOWSQL_DEST.*/a SNOWSQL_DEST="'"$SNOWSQL_DIR/bin"'"' "$SNOWSQL_DIR/$SNOWSQL_INSTALLER"
      
          echo "✅ Ensuring bin directory exists"
          mkdir -p "$SNOWSQL_DIR/bin"
      
          echo "🚀 Running the SnowSQL installer..."
          bash "$SNOWSQL_DIR/$SNOWSQL_INSTALLER" -y -d "$SNOWSQL_DIR"
          INSTALL_STATUS=$?
      
          echo "📄 Contents of $SNOWSQL_DIR after install:"
          ls -alh "$SNOWSQL_DIR"
      
          if [ $INSTALL_STATUS -ne 0 ]; then
            echo "❌ Installation failed with exit code $INSTALL_STATUS"
            exit 1
          fi
      
          echo "✅ SnowSQL installed successfully!"
          echo "🧪 Version Check:"
          "$SNOWSQL_DIR/bin/snowsql" -v
      
          # Optional: Add to PATH if needed for subsequent steps
          echo "$SNOWSQL_DIR/bin" >> $GITHUB_PATH
