name: Install and Test SnowSQL

on:
  push:

jobs:
  install-snowsql:
    runs-on: ubuntu-latest

    env:
      SNOWSQL_VERSION: 1.2.24
      SNOWSQL_DIR: $HOME/snowsql

    steps:
      - name: Print environment details (Debug)
        run: |
          echo "🖥️ OS Info:"
          uname -a
          echo "🔧 Current User:"
          whoami
          echo "📁 HOME Dir:"
          echo $HOME
          echo "🧪 Debug: SNOWSQL_VERSION=$SNOWSQL_VERSION"
          echo "🧪 Debug: SNOWSQL_DIR=$SNOWSQL_DIR"

      - name: Prepare directory and download SnowSQL installer
        run: |
          echo "📂 Creating directory $SNOWSQL_DIR..."
          mkdir -p $SNOWSQL_DIR
          
          echo "🌐 Downloading SnowSQL installer..."
          DOWNLOAD_URL="https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-${SNOWSQL_VERSION}-linux_x86_64.bash"
          echo "🔗 URL: $DOWNLOAD_URL"

          curl -L -v -o $SNOWSQL_DIR/snowsql-${SNOWSQL_VERSION}.bash "$DOWNLOAD_URL"
          DOWNLOAD_STATUS=$?

          echo "📄 Listing contents of $SNOWSQL_DIR:"
          ls -alh $SNOWSQL_DIR

          if [ $DOWNLOAD_STATUS -ne 0 ]; then
            echo "❌ Download failed with exit code $DOWNLOAD_STATUS"
            exit 1
          fi

          echo "✅ Download completed successfully."

          echo "🔐 Making installer executable..."
          chmod +x $SNOWSQL_DIR/snowsql-${SNOWSQL_VERSION}.bash

      - name: Install SnowSQL
        run: |
          echo "📦 Installing SnowSQL version $SNOWSQL_VERSION..."
          echo "📁 Installation directory: $SNOWSQL_DIR"
          echo "🚀 Executing installer script non-interactively..."
          
          # Prevent installer prompt using input redirection
          bash -x $SNOWSQL_DIR/snowsql-${SNOWSQL_VERSION}.bash -y -d $SNOWSQL_DIR < /dev/null
          INSTALL_STATUS=$?

          echo "📄 Listing contents of $SNOWSQL_DIR after installation:"
          ls -alh $SNOWSQL_DIR

          if [ $INSTALL_STATUS -ne 0 ]; then
            echo "❌ Installation failed with exit code $INSTALL_STATUS"
            exit 1
          fi

          echo "✅ Installation completed."

      - name: Add SnowSQL to PATH
        run: |
          BIN_PATH="$SNOWSQL_DIR/snowsql-${SNOWSQL_VERSION}/bin"
          echo "🔧 Adding SnowSQL bin path to \$GITHUB_PATH: $BIN_PATH"

          if [ -d "$BIN_PATH" ]; then
            echo "$BIN_PATH" >> $GITHUB_PATH
            echo "✅ SnowSQL bin path added to PATH."
          else
            echo "❌ Expected bin path does not exist: $BIN_PATH"
            ls -alh $SNOWSQL_DIR
            exit 1
          fi

      - name: Verify SnowSQL installation
        run: |
          echo "🔍 Checking if snowsql is available in PATH..."
          which snowsql || { echo "❌ SnowSQL binary not found in PATH"; exit 1; }

          echo "🧪 Running 'snowsql -v' to verify version:"
          snowsql -v || { echo "❌ SnowSQL failed to run"; exit 1; }
