env:
  SNOWSQL_VERSION: 1.4.4
  SNOWSQL_DIR: $HOME/snowsql

steps:
  - name: Prepare and download installer
    run: |
      set -ex
      mkdir -p "$SNOWSQL_DIR"
      DOWNLOAD_URL="https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.4/linux_x86_64/snowsql-${SNOWSQL_VERSION}-linux_x86_64.bash"
      curl -L -o "$SNOWSQL_DIR/snowsql-${SNOWSQL_VERSION}.bash" "$DOWNLOAD_URL"
      chmod +x "$SNOWSQL_DIR/snowsql-${SNOWSQL_VERSION}.bash"
      ls -alh "$SNOWSQL_DIR"
  
  - name: Install SnowSQL
    run: |
      set -ex
      ls -alh "$SNOWSQL_DIR"
      bash "$SNOWSQL_DIR/snowsql-${SNOWSQL_VERSION}.bash" -y -d "$SNOWSQL_DIR" || {
        echo "❌ Installer failed! Exit code $?"
        if [ -f "$SNOWSQL_DIR/install.log" ]; then
          cat "$SNOWSQL_DIR/install.log"
        else
          echo "No install.log found"
        fi
        exit 1
      }
      ls -alh "$SNOWSQL_DIR"
