name: Deploy to Snowflake manual install

on:
  push:
    branches:
      - main  # Replace with your deployment branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SNOWSQL_ACCOUNT: SPHEUCZ-HQ66596        # Replace with your Snowflake account or use GitHub Secrets
      SNOWSQL_USER: SFTRAINING                # Replace with your Snowflake user or use GitHub Secrets
      SNOWSQL_PASSWORD: GoodSuperluck2025     # Replace with your password or use GitHub Secrets securely
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SnowSQL standalone Linux binary
        run: |
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.4/linux_x86_64/snowsql-1.4.3-linux_x86_64.bash
          bash snowsql-1.4.3-linux_x86_64.bash --yes
          rm snowsql-1.4.3-linux_x86_64.bash
          echo "$HOME/.snowsql/bin" >> $GITHUB_PATH

      - name: Verify SnowSQL installation 1
        run: |
          which snowsql
          snowsql -v

      - name: Deploy SQL scripts using SnowSQL
        run: snowsql -f sql/deploy.sql  # Adjust script path as needed
