name: Deploy to Snowflake manual install

on:
  push:
    branches:
      - main  # or your preferred branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SNOWSQL_ACCOUNT: SPHEUCZ-HQ66596
      SNOWSQL_USER: SFTRAINING
      SNOWSQL_PASSWORD: GoodSuperluck2025
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python and pipx
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --user pipx
          python3 -m pipx ensurepath

      - name: Verify pipx availability and path
        run: |
          echo "PATH before adding pipx_bin:"
          echo "$PATH"
          which pipx || echo "pipx not found in PATH"
          pipx --version || echo "pipx version check failed"

      # Add the /opt/pipx_bin path to the environment for next steps (where pipx and snowsql are installed)
      - name: Add pipx bin directory to PATH for subsequent steps
        run: echo "/opt/pipx_bin" >> $GITHUB_PATH

      - name: Install Snowflake CLI manually via pipx
        run: pipx install --force snowflake-cli

      - name: Verify Snowflake CLI installation
        run: |
          which snowsql || (echo "snowsql not found in PATH" && exit 1)
          snowsql -v

      - name: Deploy SQL scripts to Snowflake
        run: snowsql -f sql/deploy.sql  # Adjust path if necessary
