name: Deploy to Snowflake Stable

on:
  push:
    branches:
      - main  # your branch here

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SNOWSQL_ACCOUNT: SPHEUCZ-HQ66596
      SNOWSQL_USER: SFTRAINING
      SNOWSQL_PASSWORD: GoodSuperluck2025
    steps:
      - uses: actions/checkout@v4

      - name: Install Snowflake CLI (Official Action)
        uses: Snowflake-Labs/snowflake-cli-action@v1.5

      - name: Add pipx bin directory to PATH
        run: echo "/opt/pipx_bin" >> $GITHUB_PATH

      - name: Verify snowsql is installed
        run: |
          which snowsql || (echo "snowsql not found in PATH" && exit 1)
          snowsql -v

      - name: Deploy SQL scripts
        run: snowsql -f sql/deploy.sql
