name: Install and Test SnowSQL

on:
  push:

jobs:
  install-snowsql:
    runs-on: ubuntu-latest

    env:
      SNOWSQL_VERSION: 1.4.4
      SNOWSQL_DIR: $HOME/snowsql

    steps:
      - name: Print environment details
        run: |
          set -ex
          echo "OS: $(uname -a)"
          echo "User: $(whoami)"
          echo "HOME: $HOME"

      - name: Download SnowSQL installer
        run: |
          set -ex
          mkdir -p $SNOWSQL_DIR
          DOWNLOAD_URL="https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.4/linux_x86_64/snowsql-${SNOWSQL_VERSION}-linux_x86_64.bash"
          curl -L -o $SNOWSQL_DIR/snowsql-${SNOWSQL_VERSION}.bash "$DOWNLOAD_URL"
          chmod +x $SNOWSQL_DIR/snowsql-${SNOWSQL_VERSION}.bash

      - name: Install SnowSQL
        run: |
          set -ex
          bash $SNOWSQL_DIR/snowsql-${SNOWSQL_VERSION}.bash -y -d $SNOWSQL_DIR

      - name: Add SnowSQL to PATH & verify install
        run: |
          set -ex
          BIN_PATH="$SNOWSQL_DIR/bin"
          if [ ! -x "$BIN_PATH/snowsql" ]; then
            echo "❌ snowsql binary not found or not executable in $BIN_PATH"
            echo "Directory listing:"
            ls -alh "$BIN_PATH"
            # Optional: Print installer log if it exists
            if [ -f "$SNOWSQL_DIR/install.log" ]; then
              echo "------ install.log ------"
              cat "$SNOWSQL_DIR/install.log"
              echo "------------------------"
            fi
            exit 1
          fi

          echo "$BIN_PATH" >> $GITHUB_PATH      # For future steps
          export PATH="$BIN_PATH:$PATH"         # For this step

          which snowsql
          snowsql -v
