name: Deploy to Snowflake manual install

on:
  push:
    branches:
      - main  # Adjust if using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SNOWSQL_ACCOUNT: SPHEUCZ-HQ66596        # Replace with your Snowflake account or use GitHub Secrets
      SNOWSQL_USER: SFTRAINING                # Replace with your Snowflake user or use GitHub Secrets
      SNOWSQL_PASSWORD: GoodSuperluck2025     # Replace with your password or use GitHub Secrets

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SnowSQL (manual with full debug)
        run: |
          set -ex  # Enable tracing and fail on error

          SNOWSQL_VERSION=1.2.24
          INSTALL_DIR=/home/runner/snowsql
          SNOWSQL_FILENAME=snowsql-${SNOWSQL_VERSION}-linux_x86_64.bash
          SNOWSQL_URL=https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/${SNOWSQL_FILENAME}

          echo "Downloading SnowSQL: $SNOWSQL_URL"
          curl -L -v -o ${SNOWSQL_FILENAME} "${SNOWSQL_URL}"

          echo "Download complete. File details:"
          ls -l ${SNOWSQL_FILENAME}
          file ${SNOWSQL_FILENAME}

          chmod +x ${SNOWSQL_FILENAME}
          mkdir -p "${INSTALL_DIR}"

          echo "Installing to ${INSTALL_DIR}..."
          DEBUG=1 yes '' | bash -x ./${SNOWSQL_FILENAME} -- -y --target "${INSTALL_DIR}"

          echo "Installed files in ${INSTALL_DIR}:"
          ls -R "${INSTALL_DIR}"

          echo "Add SnowSQL bin to PATH"
          echo "${INSTALL_DIR}/bin" >> $GITHUB_PATH
          export PATH="${INSTALL_DIR}/bin:$PATH"

          echo "Current PATH:"
          echo $PATH

          echo "Check if snowsql is in PATH:"
          ls -l $(which snowsql || echo "snowsql not found")

          echo "Try running snowsql version command directly:"
          if [ -x "${INSTALL_DIR}/bin/snowsql" ]; then
            "${INSTALL_DIR}/bin/snowsql" -v
          else
            echo "SnowSQL binary not found in expected path!"
            exit 1
          fi

      - name: Verify SnowSQL installation from PATH
        run: |
          echo "Verifying snowsql from PATH..."
          which snowsql || { echo "❌ SnowSQL not found in PATH"; exit 1; }
          snowsql -v

      - name: Deploy SQL scripts using SnowSQL
        run: |
          echo "Running deploy.sql"
          snowsql -a $SNOWSQL_ACCOUNT -u $SNOWSQL_USER -p $SNOWSQL_PASSWORD -f sql/deploy.sql
