name: Deploy SnowSQL Job

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'dev'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SnowSQL environment variables
        run: |
          echo "SNOWSQL_VERSION=1.4.4" >> $GITHUB_ENV
          echo "SNOWSQL_DIR=$HOME/snowsql" >> $GITHUB_ENV

      - name: Download SnowSQL installer
        run: |
          mkdir -p "$SNOWSQL_DIR"
          cd "$SNOWSQL_DIR"
          curl -L "https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/${SNOWSQL_VERSION}/linux_x86_64/snowsql-${SNOWSQL_VERSION}.bash" -o "snowsql-${SNOWSQL_VERSION}.bash"
        env:
          SNOWSQL_VERSION: 1.4.4
          SNOWSQL_DIR: $HOME/snowsql

      - name: Install and configure SnowSQL
        run: |
          echo "📁 Listing contents of $SNOWSQL_DIR:"
          ls -alh $SNOWSQL_DIR

          echo "🚀 Running SnowSQL installer..."
          bash $SNOWSQL_DIR/snowsql-${SNOWSQL_VERSION}.bash -y -d "$SNOWSQL_DIR"

          BIN_PATH=$(find $SNOWSQL_DIR -type d -name bin | head -n 1)
          echo "🔧 Detected BIN_PATH: $BIN_PATH"

          if [ -d "$BIN_PATH" ]; then
            echo "$BIN_PATH" >> $GITHUB_PATH  # Makes it available to *future* steps
            export PATH="$BIN_PATH:$PATH"    # Makes it available to *this* step

            echo "✅ SnowSQL bin path added to PATH."

            echo "🔍 Checking snowsql path..."
            which snowsql || { echo "❌ SnowSQL not found"; exit 1; }

            echo "🧪 Verifying SnowSQL version..."
            snowsql -v || { echo "❌ SnowSQL execution failed"; exit 1; }
          else
            echo "❌ Could not find bin path under $SNOWSQL_DIR"
            exit 1
          fi
        env:
          SNOWSQL_VERSION: 1.4.4
          SNOWSQL_DIR: $HOME/snowsql

      - name: Run your SnowSQL commands
        run: |
          echo "🎯 Running SnowSQL command..."
          snowsql -v
