name: Deploy to Snowflake manual install

on:
  push:
    branches:
      - main  # Replace with your deployment branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SNOWSQL_ACCOUNT: SPHEUCZ-HQ66596        # Replace with your Snowflake account or use GitHub Secrets
      SNOWSQL_USER: SFTRAINING                # Replace with your Snowflake user or use GitHub Secrets
      SNOWSQL_PASSWORD: GoodSuperluck2025     # Replace with your password or use GitHub Secrets securely
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SnowSQL safely
        run: |
          set -x
          curl -L -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.4/linux_x86_64/snowsql-1.4.24-linux_x86_64.bash
          chmod +x snowsql-1.4.24-linux_x86_64.bash
          ./snowsql-1.4.24-linux_x86_64.bash --yes | tee install.log
      
          # Validate
          ls -l $HOME/.snowsql/versions/1.4.24/bin/snowsql
          export PATH=$HOME/.snowsql/versions/1.4.24/bin:$PATH
          which snowsql
          snowsql -v


      - name: Verify SnowSQL installation
        run: |
          which snowsql
          snowsql -v

      - name: Deploy SQL scripts using SnowSQL
        run: snowsql -f sql/deploy.sql  # Adjust script path as needed
