name: Deploy SnowSQL Scripts to Snowflake

on:
  push

env:
  SNOWSQL_VERSION: 1.4.4
  SNOWSQL_DIR: $HOME/snowsql

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 📂 Checkout repository
        uses: actions/checkout@v4

      - name: 🧾 Print Inputs
        run: |
          echo "Environment: ${{ github.event.inputs.environment }}"

      - name: 🧪 Verify runner context
        run: |
          echo "USER: $(whoami)"
          echo "HOME: $HOME"
          echo "PWD: $(pwd)"
          echo "Shell: $SHELL"
          echo "PATH: $PATH"
          env

      - name: 📥 Download SnowSQL Installer
        run: |
          echo "🌐 Downloading SnowSQL installer..."
          mkdir -p "$SNOWSQL_DIR"
          curl -L "https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.4/linux_x86_64/snowsql-${SNOWSQL_VERSION}.bash" -o "$SNOWSQL_DIR/snowsql-${SNOWSQL_VERSION}-linux_x86_64.bash.bash"
          chmod +x "$SNOWSQL_DIR/snowsql-${SNOWSQL_VERSION}-linux_x86_64.bash.bash"
        env:
          SNOWSQL_VERSION: 1.4.4
          SNOWSQL_DIR: $HOME/snowsql


      - name: 🛠️ Install SnowSQL Non-Interactively
        run: |
          echo "📦 Installing SnowSQL version $SNOWSQL_VERSION..."
          echo "📁 Installation directory: $SNOWSQL_DIR"

          # Make sure bin directory exists
          mkdir -p "$SNOWSQL_DIR/bin"

          echo "🚀 Executing installer script non-interactively..."
          bash "$SNOWSQL_DIR/snowsql-${SNOWSQL_VERSION}.bash" -y -d "$SNOWSQL_DIR"
          INSTALL_STATUS=$?

          echo "📄 Listing contents of $SNOWSQL_DIR after installation:"
          ls -alh "$SNOWSQL_DIR"

          echo "📄 Listing contents of $SNOWSQL_DIR/bin after installation:"
          ls -alh "$SNOWSQL_DIR/bin"

          if [ $INSTALL_STATUS -ne 0 ]; then
            echo "❌ Installation failed with exit code $INSTALL_STATUS"
            exit 1
          fi

          echo "✅ Installation completed."
        env:
          SNOWSQL_VERSION: ${{ env.SNOWSQL_VERSION }}
          SNOWSQL_DIR: ${{ env.SNOWSQL_DIR }}

      - name: 🔍 Verify SnowSQL Installation
        run: |
          echo "🔍 Checking if snowsql is available in PATH..."
          export PATH="$SNOWSQL_DIR/bin:$PATH"

          echo "📁 Listing $SNOWSQL_DIR contents for debug:"
          ls -alh "$SNOWSQL_DIR"

          echo "🧪 Contents of bin:"
          ls -alh "$SNOWSQL_DIR/bin"

          echo "📍 PATH: $PATH"

          which snowsql || { echo "❌ SnowSQL binary not found in PATH"; exit 1; }

          echo "🧪 Running 'snowsql -v' to verify version:"
          snowsql -v || { echo "❌ SnowSQL failed to run"; exit 1; }
        env:
          SNOWSQL_DIR: ${{ env.SNOWSQL_DIR }}
