name: Deploy to Snowflake manual install

on:
  push:
    branches:
      - main  # Adjust if using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SNOWSQL_ACCOUNT: SPHEUCZ-HQ66596        # Replace with your Snowflake account or use GitHub Secrets
      SNOWSQL_USER: SFTRAINING                # Replace with your Snowflake user or use GitHub Secrets
      SNOWSQL_PASSWORD: GoodSuperluck2025     # Replace with your password or use GitHub Secrets

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SnowSQL (manual .bash installer)
        run: |
          set -ex  # enable command tracing and exit on any error
          
          SNOWSQL_VERSION=1.2.24
          INSTALL_DIR=/home/runner/snowsql
          SNOWSQL_FILENAME=snowsql-${SNOWSQL_VERSION}-linux_x86_64.bash
          SNOWSQL_URL=https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/${SNOWSQL_FILENAME}
          
          echo "Downloading SnowSQL from: ${SNOWSQL_URL}"
          curl -L -v -o ${SNOWSQL_FILENAME} "${SNOWSQL_URL}"  # add -v for verbose curl output
          
          echo "Downloaded file:"
          ls -l ${SNOWSQL_FILENAME}
          file ${SNOWSQL_FILENAME}  # inspect the file type to ensure it’s valid
          
          chmod +x ${SNOWSQL_FILENAME}
          
          mkdir -p "${INSTALL_DIR}"
          echo "Running installer..."
          
          # Run the installer with debugging env vars
          DEBUG=1 bash -x ./${SNOWSQL_FILENAME} -- -y --target "${INSTALL_DIR}"
          
          echo "Installation directory contents:"
          ls -R "${INSTALL_DIR}"
          

      - name: Verify SnowSQL installation
        run: |
          which snowsql
          snowsql -v

      - name: Deploy SQL scripts using SnowSQL
        run: snowsql -f sql/deploy.sql  # Adjust path to your SQL file
