# .github/workflows/snowsql-install.yml
name: Install and Test SnowSQL

on:
  push:

jobs:
  install-snowsql:
    runs-on: ubuntu-latest

    env:
      SNOWSQL_VERSION: 1.4.4
      SNOWSQL_DIR: $HOME/snowsql

    steps:
      - name: Download SnowSQL installer
        run: |
          mkdir -p $SNOWSQL_DIR
          curl -L -o $SNOWSQL_DIR/snowsql-${SNOWSQL_VERSION}.bash \
            https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.4/linux_x86_64/snowsql-${SNOWSQL_VERSION}-linux_x86_64.bash
          chmod +x $SNOWSQL_DIR/snowsql-${SNOWSQL_VERSION}.bash

      - name: Install SnowSQL
        run: |
          bash $SNOWSQL_DIR/snowsql-${SNOWSQL_VERSION}.bash -y -d $SNOWSQL_DIR

      - name: Add SnowSQL to PATH
        run: |
          echo "$SNOWSQL_DIR/snowsql-${SNOWSQL_VERSION}/bin" >> $GITHUB_PATH

      - name: Verify SnowSQL installation
        run: |
          echo "Verifying snowsql from PATH..."
          which snowsql || { echo "❌ SnowSQL not found in PATH"; exit 1; }
          snowsql -v
 
