name: Deploy to Snowflake manual install

on:
  push:
    branches:
      - main  # Replace with your deployment branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SNOWSQL_ACCOUNT: SPHEUCZ-HQ66596        # Replace with your Snowflake account or use GitHub Secrets
      SNOWSQL_USER: SFTRAINING                # Replace with your Snowflake user or use GitHub Secrets
      SNOWSQL_PASSWORD: GoodSuperluck2025     # Replace with your password or use GitHub Secrets

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SnowSQL (manual .bash installer)
        run: |
          set -ex
          
          # Define variables
          SNOWSQL_VERSION="1.4.3"
          INSTALL_DIR="$HOME/snowsql"
          SNOWSQL_FILENAME="snowsql-${SNOWSQL_VERSION}-linux_x86_64.bash"
          SNOWSQL_URL="https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.4/linux_x86_64/${SNOWSQL_FILENAME}"
          
          # Download installer
          echo "Downloading SnowSQL from $SNOWSQL_URL..."
          curl -L -o "$SNOWSQL_FILENAME" "$SNOWSQL_URL"
          
          # Ensure download is successful
          if [[ ! -f "$SNOWSQL_FILENAME" ]]; then
            echo "❌ Installer not found: $SNOWSQL_FILENAME"
            exit 1
          fi

          # Make installer executable
          chmod +x "$SNOWSQL_FILENAME"

          # Create install directory and run installer
          mkdir -p "$INSTALL_DIR"
          "./$SNOWSQL_FILENAME" --target "$INSTALL_DIR" --yes

          # Add SnowSQL to PATH for this job
          echo "$INSTALL_DIR/snowsql/bin" >> "$GITHUB_PATH"

      - name: Verify SnowSQL installation
        run: |
          which snowsql
          snowsql -v

      - name: Deploy SQL scripts using SnowSQL
        run: snowsql -f sql/deploy.sql  # Adjust the path to your actual SQL file
