name: Install and Debug SnowSQL

on:
  push:

jobs:
  install-snowsql:
    runs-on: ubuntu-latest

    env:
      SNOWSQL_VERSION: 1.4.4
      SNOWSQL_DIR: $HOME/snowsql

    steps:
      - name: Print Environment Details
        run: |
          set -ex
          echo "HOME=$HOME"
          echo "SNOWSQL_DIR=$SNOWSQL_DIR"
          echo "PATH=$PATH"

      - name: Prepare Directory and Download SnowSQL Installer
        run: |
          set -ex
          mkdir -p "$SNOWSQL_DIR"
          DOWNLOAD_URL="https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.4/linux_x86_64/snowsql-${SNOWSQL_VERSION}-linux_x86_64.bash"
          curl -L -o "$SNOWSQL_DIR/snowsql-${SNOWSQL_VERSION}.bash" "$DOWNLOAD_URL"
          chmod +x "$SNOWSQL_DIR/snowsql-${SNOWSQL_VERSION}.bash"
          ls -alh "$SNOWSQL_DIR"

      - name: Install SnowSQL (with debug)
        run: |
          set -ex
          ls -alh "$SNOWSQL_DIR"
          bash "$SNOWSQL_DIR/snowsql-${SNOWSQL_VERSION}.bash" -y -d "$SNOWSQL_DIR" || {
            echo "Installer failed!"
            if [ -f "$SNOWSQL_DIR/install.log" ]; then
              cat "$SNOWSQL_DIR/install.log"
           fi
            exit 1
          }
          ls -alh "$SNOWSQL_DIR"

      - name: Add SnowSQL to PATH and verify
        run: |
          set -ex
          echo "$SNOWSQL_DIR/bin" >> $GITHUB_PATH
          export PATH="$SNOWSQL_DIR/bin:$PATH"
          which snowsql
          snowsql -v
