name: Deploy to Snowflake manual install

on:
  push:
    branches:
      - main  # Adjust if using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SNOWSQL_ACCOUNT: SPHEUCZ-HQ66596        # Replace with your Snowflake account or use GitHub Secrets
      SNOWSQL_USER: SFTRAINING                # Replace with your Snowflake user or use GitHub Secrets
      SNOWSQL_PASSWORD: GoodSuperluck2025     # Replace with your password or use GitHub Secrets

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SnowSQL (manual .bash installer with debug)
        run: |
          set -ex

          SNOWSQL_VERSION=1.2.24
          SNOWSQL_FILENAME=snowsql-${SNOWSQL_VERSION}-linux_x86_64.bash
          SNOWSQL_URL=https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/${SNOWSQL_FILENAME}

          echo "Downloading SnowSQL from: ${SNOWSQL_URL}"
          curl -L -v -o ${SNOWSQL_FILENAME} "${SNOWSQL_URL}"
          chmod +x ${SNOWSQL_FILENAME}

          echo "Installing to default location (~/.snowsql)..."
          DEBUG=1 yes '' | bash -x ./${SNOWSQL_FILENAME} -- -y

          echo "Installed structure:"
          ls -R ~/.snowsql

          # Add correct path to SnowSQL binary to GITHUB_PATH
          echo "$HOME/.snowsql/${SNOWSQL_VERSION}/scripts" >> $GITHUB_PATH

      - name: Verify SnowSQL installation from PATH
        run: |
          echo "Verifying snowsql from PATH..."
          which snowsql || { echo "❌ SnowSQL not found in PATH"; exit 1; }
          snowsql -v

      - name: Deploy SQL scripts using SnowSQL
        run: |
          echo "Running deploy.sql"
          snowsql -a $SNOWSQL_ACCOUNT -u $SNOWSQL_USER -p $SNOWSQL_PASSWORD -f sql/deploy.sql
