name: Deploy to Snowflake new

on:
  push:
    branches:
      - main  # or whichever branch you want to trigger the deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SNOWSQL_ACCOUNT: SPHEUCZ-HQ66596
      SNOWSQL_USER: SFTRAINING
      SNOWSQL_PASSWORD: GoodSuperluck2025
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print env and PATH 1
        run: |
          echo "PATH before Snowflake CLI install:"
          echo $PATH
          env

      - name: Install Snowflake CLI
        uses: Snowflake-Labs/snowflake-cli-action@v1.5

      # Add pipx's bin directory to PATH explicitly for subsequent steps
      - name: Add pipx bin directory to PATH
        run: echo "/opt/pipx_bin" >> $GITHUB_PATH

      - name: Print env and PATH 2
        run: |
          echo "PATH after adding pipx_bin:"
          echo $PATH
          env

      - name: Check Snowflake CLI version
        run: |
          which snowsql
          snowsql -v

      - name: Deploy SQL scripts
        run: snowsql -f sql/deploy.sql   # adjust the path if needed
